### ISSUE TITLE
Attempt to have a second RNNCell use the weights of a variable scope that already has weights

### ISSUE THREAD

**Issue by flsd201983** [zsdonghao/text-to-image#2]
I got a problem, how can I solve it? 

Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'rnnftxt/rnn/dynamic/rnn/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.

**Comment by zsdonghao** [comment]
simply add ` cell_init_args = {'state_is_tuple' : True, 'reuse': reuse}` into `DynamicRNNLayer` if you are using TF1.1
